return {
  -- disable
  -- overrides
  { import = "plugins.override.conform" },
  { import = "plugins.override.gitsigns" },
  { import = "plugins.override.indent-blankline" },
  { import = "plugins.override.lspconfig" },
  { import = "plugins.override.mason" },
  { import = "plugins.override.nvimtree" },
  { import = "plugins.override.telescope" },
  { import = "plugins.override.treesitter" },
  -- add
  { import = "plugins.add.actions-preview" },
  { import = "plugins.add.aerial" },
  { import = "plugins.add.avante" },
  -- { import = "plugins.add.codeium" },
  { import = "plugins.add.comment" },
  { import = "plugins.add.copilot" },
  { import = "plugins.add.crates" },
  { import = "plugins.add.diffview" },
  { import = "plugins.add.local-highlight" },
  { import = "plugins.add.lsp-endhints" },
  { import = "plugins.add.markdown" },
  { import = "plugins.add.neoscroll" },
  { import = "plugins.add.noice" },
  { import = "plugins.add.plantuml" },
  { import = "plugins.add.rustaceanvim" },
  { import = "plugins.add.smartyank" },
  { import = "plugins.add.spectre" },
  { import = "plugins.add.suda" },
  { import = "plugins.add.tiny-inline-diagnostic" },
  { import = "plugins.add.todo-comment" },
  { import = "plugins.add.trailspace" },
}
